# Hugo configuration
baseURL = "https://nextredo.github.io/brojs/"
title = "BroJS Hugo Theme"

[module]
  [module.hugoVersion]
    min = "0.146.0"

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 2

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 3

  [[menus.main]]
    name = "About"
    pageRef = "/about/"
    weight = 4


# Custom parameters
[params]
  repo_url = "https://github.com/nextredo/brojs"

  # The licensing of your website
  [params.license]
    copyright = "other"
    name = "AGPLv3"
    link = "https://www.gnu.org/licenses/agpl-3.0.en.html"
    # Important to *NOT* have a leading "/" in the image path
    image = "images/agplv3-license.png"
