name: post-deployment

on:
  workflow_run:
    # Match GitHub pages inbuilt action
    workflows: ["pages-build-deployment"]
    types: [completed]

jobs:
  after-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -x {0} # Print commands before execution

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Wait
        run: |
          # Unnecessary sleep to allow site to fully update
          sleep 20

      - name: To proceed or not to proceed?
        # TODO this instead vv
        # if: ${{ github.event.workflow_run.conclusion }} == 'success'
        run: |
          echo "Pages deployment finished with: ${{ github.event.workflow_run.conclusion }}"

          # Quit if deployment failed
          if [ "${{ github.event.workflow_run.conclusion }}" = "success" ]; then
            echo "Continuing"
          else
            exit 1
          fi

      - name: Install dependencies
        run: |
          # Install dependencies
          sudo apt-get update
          sudo apt-get install -y nodejs npm
          sleep 2

      - name: Install Puppeteer
        run: |
          # Setup work dir, install Puppeteer
          # Puppeteer automatically installs a chromium version to use
          mkdir /tmp/shotter
          cd /tmp/shotter
          npm init -y
          npm install puppeteer
          sleep 2

      - name: Generate homepage screenshot
        run: |
          # Get the runner from the primary branch
          cp ${{ github.workspace }}/.github/workflows/screenshotter.js /tmp/shotter/

          # Run the screenshotter, now that the website has been published
          cd /tmp/shotter
          node ./screenshotter.js ${{ github.workspace }} ${{ github.event.deployment_status.environment_url }}
          sleep 2

      - name: Commit homepage screenshot
        run: |
          cd ${{ github.workspace }}

          # Setup git
          git config --local user.name "${{ github.triggering_actor }}"
          git config --local user.email "${{ github.triggering_actor }}@users.noreply.github.com"
          git add ./images/screenshot.png

          # Commit if changes exist
          git diff-index --quiet HEAD || git commit -m "Screenshot update"
          git push
