name: post-deployment

on:
  workflow_run:
    # Match GitHub pages inbuilt action
    workflows: ["pages-build-deployment"]
    types: [completed]

permissions:
  contents: write

jobs:
  after-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -x {0} # Print commands before execution

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: To proceed or not to proceed?
        # TODO this instead vv
        if: ${{ github.event.workflow_run.conclusion }} == 'success'
        run: |
          sleep 5

      - name: Wait a little for site update
        run: |
          # Unnecessary sleep to allow site to fully update
          sleep 15

      - name: Install node, npm
        run: |
          # Install dependencies
          sudo apt-get update
          sudo apt-get install -y nodejs npm
          sleep 2

      - name: Install Puppeteer
        run: |
          # Setup work dir
          mkdir /tmp/shotter
          cd /tmp/shotter

          # Install Puppeteer
          # Puppeteer automatically installs a chromium version to use
          npm init -y
          npm install puppeteer
          sleep 2

      - name: Generate homepage screenshot
        run: |
          cd /tmp/shotter

          # Get the runner from the primary branch
          cp ${{ github.workspace }}/.github/workflows/screenshotter.js /tmp/shotter/

          # Run the screenshotter, now that the website has been published
          node ./screenshotter.js ${{ github.workspace }} "https://nextredo.github.io/brojs/"
          sleep 2

      - name: Commit homepage screenshot
        run: |
          cd ${{ github.workspace }}

          # Setup git
          git checkout gh-pages
          git config --local user.name "${{ github.actor }}"
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git add ./images/screenshot.png

          # Commit if changes exist
          git diff-index --quiet HEAD || git commit -m "ci: post deploy update"
          git push
